### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by DeeJaVu** [falsovsky/chaturbate#14]
im getting error when running the script

```
INFO Model BlaBlaBla is chaturbating
Traceback (most recent call last):
  File "chaturbate.py", line 632, in <module>
    c.do_cycle()
  File "chaturbate.py", line 514, in do_cycle
    self.process_models(online_models)
  File "chaturbate.py", line 339, in process_models
    info = self.get_flv_info(model)
  File "chaturbate.py", line 368, in get_flv_info
    data = re.search(r" +[\"'](.*)?[\"'],", line)
  File "/usr/lib64/python2.7/re.py", line 142, in search
    return _compile(pattern, flags).search(string)
  File "/usr/lib64/python2.7/re.py", line 242, in _compile
    raise error, v # invalid expression
sre_constants.error: nothing to repeat
```

**Comment by falsovsky** [comment]
You're not running the current version of the script, because the lines dont match.

**Comment by DeeJaVu** [comment]
why are you closing it ?????????????????

i am using the current script

**Comment by falsovsky** [comment]
The lines dont match. Please update it.

**Comment by falsovsky** [comment]
Well, im sorry, i was looking at a newer version :-)

**Comment by DeeJaVu** [comment]
Oh ok

**Comment by falsovsky** [comment]
Show me the output of: 
python2 --version

**Comment by DeeJaVu** [comment]
Python 2.7.5

i will upgrade my python Thx
