### ISSUE TITLE
Few issues.

### ISSUE THREAD

**Issue by chopraaa** [falsovsky/chaturbate#7]
1. First is the need to run `cp librtmp.so.1 /usr/lib/x86_64-linux-gnu/librtmp.so.1`. I've tested this from the latest rtmpdump build, then running KSV's patch myself, and also by using the rmpdump-ksv repository that's linked in the readme.

2. Script dies on it's own after some time, doesn't matter if I'm running it in screen or not. 

```
2017-02-06 15:01:38 INFO ashlyeroberts is no longer being captured
Traceback (most recent call last):
  File "chaturbate.py", line 633, in <module>
    c.do_cycle()
  File "chaturbate.py", line 512, in do_cycle
    c.is_running()
  File "chaturbate.py", line 436, in is_running
    self.clean_rtmpdump(process)
  File "chaturbate.py", line 415, in clean_rtmpdump
    self.move_to_complete(process_info)
  File "chaturbate.py", line 594, in move_to_complete
    self.run_ffmpeg(process['model'], flv, mp4)
  File "chaturbate.py", line 616, in run_ffmpeg
    stderr=DEVNULL)
  File "/usr/lib/python2.7/subprocess.py", line 710, in __init__
    errread, errwrite)
  File "/usr/lib/python2.7/subprocess.py", line 1335, in _execute_child
    raise child_exception
OSError: [Errno 2] No such file or directory
```
3. ffmpeg conversion isn't successful, at all.

**Comment by falsovsky** [comment]
Hi,

I recommend to stop using the ffmpeg processing, as it has bugs, I havent been able to fix it.

**Comment by chopraaa** [comment]
I wish I could help with this but I really suck at Python. And by suck I mean I can't do shit.

Also, `libfaac` is deprecated and support has been used. Just use `aac` or `libfdk_aac` if you plan on fixing the ffmpeg part.
